export const LOADING_QUOTES = Object.freeze([
  "Consulting the tile goblins. They demand vowels.",
  "Calculating how to ruin a perfectly friendly game.",
  "Finding a word your opponent will definitely question.",
  "Turning innocent letters into relationship problems.",
  "Searching for points. Sportsmanship is on another server.",
  "Asking the dictionary to lower its standards.",
  "Preparing a move that looks suspiciously well informed.",
  "Counting squares because apparently this is who we are now.",
  "Looking for a tasteful way to use the triple word score.",
  "Rearranging letters with completely natural human speed.",
  "Checking whether smugness receives a bingo bonus.",
  "Teaching seven tiles the meaning of teamwork.",
  "Politely weaponising the alphabet.",
  "Looking busy while the computer does everything.",
  "Finding the shortest route to an awkward rematch.",
  "Auditing your vowels for underperformance.",
  "Making random tiles look like a deliberate strategy.",
  "Calculating exactly how annoyed your opponent might become.",
  "Searching SOWPODS for something deeply unreasonable.",
  "Converting friendship into points. Please wait.",
  "Checking every word except the obvious one you missed.",
  "Warming up the deterministic mischief engine.",
  "Preparing plausible deniability.",
  "Finding a move you can pretend you spotted immediately.",
  "Scanning the board for premium-grade bad manners.",
  "Giving your rack the management consultancy it deserves.",
  "Locating the square labelled future regret.",
  "Making the Q somebody else's emotional burden.",
  "Searching for a word worth an unnecessary victory dance.",
  "Optimising letters. De-optimising trust.",
  "Checking if that nonsense word is, annoyingly, legal.",
  "Assembling a completely organic 84-point move.",
  "Finding new and exciting ways to say your turn.",
  "Running advanced mathematics on a game played in bed.",
  "Asking the consonants to stop forming a committee.",
  "Looking for somewhere expensive to put an X.",
  "Preparing the traditional post-move dictionary argument.",
  "Making your opponent regret enabling notifications.",
  "Searching for tactical brilliance to borrow temporarily.",
  "Examining the board with entirely normal intensity.",
  "Finding a word no one has used since 1742.",
  "Checking whether rage-quitting counts as a valid response.",
  "Putting the artificial in your natural talent.",
  "Calculating the optimal amount of casual confidence.",
  "Looking for points in all the morally grey places.",
  "Preparing to act surprised by the result.",
  "Scanning 267,000 words so you don't have to think.",
  "Finding the move your rack was trying to hide.",
  "Negotiating a better deal with the letter distribution.",
  "Checking if seven vowels can file for compensation.",
  "Constructing a word and a convincing backstory.",
  "Finding something legal, if not emotionally acceptable.",
  "Analysing premiums with the seriousness they clearly deserve.",
  "Turning one screenshot into several trust issues.",
  "Checking for bingos and other acts of aggression.",
  "Finding a move that says I definitely knew that word.",
  "Calculating first. Gloating responsibly later.",
  "Looking for a triple word and a tiny moral loophole.",
  "Preparing seven letters for hostile deployment.",
  "Searching for vocabulary beyond your alleged reading level.",
  "Making sure the blank tile takes all the credit.",
  "Checking whether subtlety fits on the board. It does not.",
  "Finding the mathematically correct amount of audacity.",
  "Preparing a move best described as technically allowed.",
  "Scanning for opportunities to become unbearable.",
  "Giving the dictionary a deeply suspicious workout.",
  "Finding points your opponent carelessly left unattended.",
  "Calculating how to look lucky with maximum precision.",
  "Looking for a word that requires immediate Googling.",
  "Preparing to casually drop an obscure plural.",
  "Checking the board twice. Trusting you zero times.",
  "Finding a premium square in need of adult supervision.",
  "Turning alphabet soup into competitive hostility.",
  "Calculating your next completely spontaneous masterpiece.",
  "Searching for the move that ends the group chat.",
  "Asking SOWPODS what fresh nonsense it has today.",
  "Finding the optimal word and an excuse for knowing it.",
  "Preparing a move with excellent legal representation.",
  "Checking whether humility can be exchanged for vowels.",
  "Running the numbers while you practise looking innocent.",
  "Finding a word your autocorrect would report as abuse.",
  "Calculating maximum points per unit of friendship.",
  "Searching for a tasteful amount of devastation.",
  "Making the board regret having premium squares.",
  "Preparing the alphabet for another regrettable incident.",
  "Finding a move with strong main-character energy.",
  "Checking if your opponent has started typing already.",
  "Optimising the board beyond reasonable social limits.",
  "Looking for a word that sounds confidently invented.",
  "Preparing a tiny linguistic ambush.",
  "Finding the best move. Mercy remains optional.",
  "Checking all possibilities, including excessive smugness.",
  "Turning your rack into somebody else's bad evening.",
  "Searching for the least believable lucky guess.",
  "Calculating a move your opponent will screenshot too.",
  "Finding hidden value in letters you were about to swap.",
  "Preparing an educational moment nobody requested.",
  "Checking whether the dictionary can keep a secret.",
  "Finding a move that is both valid and deeply irritating.",
  "Loading tactical vocabulary and recreational treachery."
]);

export function randomLoadingQuote() {
  const random=new Uint32Array(1);
  if(globalThis.crypto?.getRandomValues)globalThis.crypto.getRandomValues(random);
  else random[0]=Math.floor(Math.random()*2**32);
  return LOADING_QUOTES[random[0]%LOADING_QUOTES.length];
}
